[package]
name = "opinion_organizers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7"
map-macro = "0.2.5"
lazy_static = "1.4.0"
regex = "1.7.3"
